name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    # setup Java environment in order to build  Android app.
    - uses: actions/setup-java@v1
      with:
        java-version: '13.x'
    # setup the flutter environment
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Check for formatting issues
      run: flutter format --set-exit-if-changed
    - name: Analyze dart code for errors
      run: flutter analyze .
    - name: Run widget tests
      run: flutter test
    - name: Build apk
      run: flutter build apk
    
    # Upload generated apk to the artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
